### ISSUE TITLE
Support JS

### ISSUE THREAD

**Issue by luca992** [ACINQ/secp256k1-kmp#51] opened 2022-04-04 08:55 UTC
Any plans to add js as a target? It would be nice, even if just delegates to a npm dependency like: https://www.npmjs.com/package/secp256k1

**Comment by t-bast** [comment] 2022-04-04 08:56
Duplicate of https://github.com/ACINQ/secp256k1-kmp/issues/26

**Closed by t-bast** 2022-04-04 08:56 UTC
